import { Restaurant, Product, GroceryStore, ServiceArea, Coupon, User, Order } from '@/types';

export const SEED_USERS: User[] = [
  {
    id: 'user-customer-1',
    name: 'Anas Ahmed',
    email: 'customer@zestora.com',
    phone: '+91 98765 43210',
    role: 'CUSTOMER',
    passwordHash: 'hashed:customer123', // plaintext equivalent: customer123
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-admin-1',
    name: 'Zestora Admin',
    email: 'admin@zestora.com',
    phone: '+91 90000 00001',
    role: 'ADMIN',
    passwordHash: 'hashed:admin123', // plaintext equivalent: admin123
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-restaurant-1',
    name: 'Tariq - Spice Garden',
    email: 'spicegarden@zestora.local',
    phone: '+91 98800 11223',
    role: 'RESTAURANT_OWNER',
    passwordHash: 'hashed:rest123',
    avatar: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-delivery-1',
    name: 'Rahul Naik',
    email: 'rahul.rider@zestora.local',
    phone: '+91 94488 55667',
    role: 'DELIVERY_PARTNER',
    passwordHash: 'hashed:rider123',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
];


export const SEED_SERVICE_AREAS: ServiceArea[] = [
  {
    id: 'area-1',
    city: 'Bhatkal',
    zoneName: 'Bhatkal Central',
    postalCode: '581320',
    radiusKm: 3.5,
    baseDelivery: 20,
    minOrder: 100,
    surgeFee: 0,
    isActive: true,
  },
  {
    id: 'area-2',
    city: 'Bhatkal',
    zoneName: 'Sonar Keri & Bunder',
    postalCode: '581320',
    radiusKm: 6.0,
    baseDelivery: 35,
    minOrder: 150,
    surgeFee: 0,
    isActive: true,
  },
  {
    id: 'area-3',
    city: 'Bhatkal',
    zoneName: 'Nawayath Colony & Outskirts',
    postalCode: '581320',
    radiusKm: 10.0,
    baseDelivery: 60,
    minOrder: 200,
    surgeFee: 10,
    isActive: true,
  },
];

export const SEED_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'ZEST50',
    type: 'PERCENTAGE',
    discountValue: 50,
    minimumOrder: 299,
    maxDiscount: 100,
    description: '50% OFF up to ₹100 on orders above ₹299',
    isActive: true,
  },
  {
    id: 'coup-2',
    code: 'FREEDEL',
    type: 'FREE_DELIVERY',
    discountValue: 100,
    minimumOrder: 199,
    maxDiscount: 35,
    description: 'Free delivery on all orders above ₹199',
    isActive: true,
  },
  {
    id: 'coup-3',
    code: 'WELCOME100',
    type: 'FIXED_AMOUNT',
    discountValue: 100,
    minimumOrder: 399,
    maxDiscount: 100,
    description: 'Flat ₹100 instant discount on orders above ₹399',
    isActive: true,
  },
];

export const SEED_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'Spice Garden',
    slug: 'spice-garden-bhatkal',
    ownerId: 'user-restaurant-1',
    description: 'Finest Indo-Chinese and Coastal specialties with authentic aromatic herbs.',
    cuisine: 'North Indian • Chinese • Tandoor',
    logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&auto=format&fit=crop&q=80',
    rating: 4.6,
    ratingCount: 842,
    deliveryTimeMin: 25,
    deliveryTimeMax: 35,
    deliveryFee: 30,
    minimumOrder: 150,
    commissionRate: 0.20,
    isOpen: true,
    isVerified: true,
    addressLine: 'Near Eidgah Ground, Main Road',
    area: 'Bhatkal Central',
    city: 'Bhatkal',
    latitude: 13.9872,
    longitude: 74.5612,
    menuCategories: [
      {
        id: 'cat-1',
        restaurantId: 'rest-1',
        name: 'Recommended & Chef Specials',
        sortOrder: 1,
        items: [
          {
            id: 'item-1',
            restaurantId: 'rest-1',
            categoryId: 'cat-1',
            name: 'Special Chicken Biryani (Bhatkali Style)',
            description: 'Fragrant short-grain rice layered with slow-cooked marinated chicken, saffron, fried onions, and signature spices.',
            price: 240,
            image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=80',
            isVeg: false,
            isAvailable: true,
            preparationTime: 20,
            spiceLevel: 'Medium',
            rating: 4.8,
            variants: [
              { id: 'var-1', name: 'Regular', price: 240 },
              { id: 'var-2', name: 'Jumbo Pack', price: 440 },
            ],
            addons: [
              { id: 'add-1', name: 'Extra Egg', price: 20 },
              { id: 'add-2', name: 'Raita & Mirchi Salan', price: 30 },
            ],
          },
          {
            id: 'item-2',
            restaurantId: 'rest-1',
            categoryId: 'cat-1',
            name: 'Paneer Butter Masala',
            description: 'Cottage cheese cubes bathed in rich creamy tomato cashew gravy with fenugreek butter.',
            price: 210,
            image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&auto=format&fit=crop&q=80',
            isVeg: true,
            isAvailable: true,
            preparationTime: 15,
            spiceLevel: 'Mild',
            rating: 4.6,
            variants: [
              { id: 'var-3', name: 'Half (300ml)', price: 140 },
              { id: 'var-4', name: 'Full (600ml)', price: 210 },
            ],
            addons: [
              { id: 'add-3', name: 'Extra Butter', price: 20 },
              { id: 'add-4', name: 'Butter Naan (2 pcs)', price: 60 },
            ],
          },
        ],
      },
      {
        id: 'cat-2',
        restaurantId: 'rest-1',
        name: 'Tandoor & Starters',
        sortOrder: 2,
        items: [
          {
            id: 'item-3',
            restaurantId: 'rest-1',
            categoryId: 'cat-2',
            name: 'Crispy Chicken Ghee Roast',
            description: 'Kundapur coastal masala roasted in pure clarified butter with curry leaves.',
            price: 260,
            image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=80',
            isVeg: false,
            isAvailable: true,
            preparationTime: 18,
            spiceLevel: 'Spicy',
            rating: 4.9,
          },
          {
            id: 'item-4',
            restaurantId: 'rest-1',
            categoryId: 'cat-2',
            name: 'Tandoori Garlic Naan',
            description: 'Clay-oven baked leavened bread topped with fresh crushed garlic and butter.',
            price: 45,
            image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80',
            isVeg: true,
            isAvailable: true,
            preparationTime: 10,
            rating: 4.7,
          },
        ],
      },
    ],
  },
  {
    id: 'rest-2',
    name: 'Coastal Bites',
    slug: 'coastal-bites-bhatkal',
    ownerId: 'user-restaurant-1',
    description: 'Fresh Arabian Sea catches, surmai tawa fry, prawn ghee roast, and coastal fish curries.',
    cuisine: 'Coastal Seafood • Mangalorean • South Indian',
    logo: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=1200&auto=format&fit=crop&q=80',
    rating: 4.8,
    ratingCount: 1120,
    deliveryTimeMin: 20,
    deliveryTimeMax: 30,
    deliveryFee: 25,
    minimumOrder: 180,
    commissionRate: 0.20,
    isOpen: true,
    isVerified: true,
    addressLine: 'Bunder Road, Coastal Promenade',
    area: 'Sonar Keri & Bunder',
    city: 'Bhatkal',
    latitude: 13.9789,
    longitude: 74.5498,
    menuCategories: [
      {
        id: 'cat-cb-1',
        restaurantId: 'rest-2',
        name: 'Catch of the Day',
        sortOrder: 1,
        items: [
          {
            id: 'item-cb-1',
            restaurantId: 'rest-2',
            categoryId: 'cat-cb-1',
            name: 'Surmai / Kingfish Tawa Fry',
            description: 'Locally caught fresh Kingfish marinated in spicy red chili kokum paste and shallow tawa-fried in coconut oil.',
            price: 320,
            image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500&auto=format&fit=crop&q=80',
            isVeg: false,
            isAvailable: true,
            preparationTime: 20,
            spiceLevel: 'Spicy',
            rating: 4.9,
          },
          {
            id: 'item-cb-2',
            restaurantId: 'rest-2',
            categoryId: 'cat-cb-1',
            name: 'Prawns Ghee Roast with Neer Dosa',
            description: 'Juicy tiger prawns roasted in byadgi chilli paste served with 3 melt-in-mouth soft neer dosas.',
            price: 340,
            image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=500&auto=format&fit=crop&q=80',
            isVeg: false,
            isAvailable: true,
            preparationTime: 22,
            spiceLevel: 'Spicy',
            rating: 4.8,
          },
        ],
      },
    ],
  },
  {
    id: 'rest-3',
    name: 'Biryani House',
    slug: 'biryani-house-bhatkal',
    ownerId: 'user-restaurant-1',
    description: 'Legendary white Bhatkali dum biryani with tender mutton, caramelized onions, and homemade masala.',
    cuisine: 'Biryani • Mughlai • Kebabs',
    logo: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=1200&auto=format&fit=crop&q=80',
    rating: 4.9,
    ratingCount: 1870,
    deliveryTimeMin: 20,
    deliveryTimeMax: 30,
    deliveryFee: 25,
    minimumOrder: 150,
    commissionRate: 0.20,
    isOpen: true,
    isVerified: true,
    addressLine: 'Old Town Market Circle',
    area: 'Bhatkal Central',
    city: 'Bhatkal',
    latitude: 13.9855,
    longitude: 74.5588,
    menuCategories: [
      {
        id: 'cat-bh-1',
        restaurantId: 'rest-3',
        name: 'Authentic Dum Biryanis',
        sortOrder: 1,
        items: [
          {
            id: 'item-bh-1',
            restaurantId: 'rest-3',
            categoryId: 'cat-bh-1',
            name: 'Heritage Mutton Dum Biryani',
            description: 'Slow pot-cooked tender mutton cooked on charcoal embers with premium basmati rice and saffron milk.',
            price: 310,
            image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=500&auto=format&fit=crop&q=80',
            isVeg: false,
            isAvailable: true,
            preparationTime: 15,
            spiceLevel: 'Medium',
            rating: 5.0,
            variants: [
              { id: 'bh-v1', name: 'Standard Box', price: 310 },
              { id: 'bh-v2', name: 'Family Handi (3-4 Servings)', price: 850 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'rest-4',
    name: 'Pizza Street',
    slug: 'pizza-street-bhatkal',
    ownerId: 'user-restaurant-1',
    description: 'Stone-baked artisan thin crust pizzas, cheesy garlic breads, and Italian pasta.',
    cuisine: 'Pizza • Italian • Fast Food',
    logo: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=1200&auto=format&fit=crop&q=80',
    rating: 4.7,
    ratingCount: 650,
    deliveryTimeMin: 25,
    deliveryTimeMax: 35,
    deliveryFee: 30,
    minimumOrder: 200,
    commissionRate: 0.20,
    isOpen: true,
    isVerified: true,
    addressLine: 'Commercial Complex, Near Circle',
    area: 'Bhatkal Central',
    city: 'Bhatkal',
    latitude: 13.9888,
    longitude: 74.5633,
    menuCategories: [
      {
        id: 'cat-ps-1',
        restaurantId: 'rest-4',
        name: 'Gourmet Wood-Fired Pizzas',
        sortOrder: 1,
        items: [
          {
            id: 'item-ps-1',
            restaurantId: 'rest-4',
            categoryId: 'cat-ps-1',
            name: 'Peri-Peri Chicken Fiesta Pizza',
            description: 'Fiery grilled peri-peri chicken chunks, spicy jalapeños, bell peppers, and melted mozzarella.',
            price: 299,
            image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&auto=format&fit=crop&q=80',
            isVeg: false,
            isAvailable: true,
            preparationTime: 20,
            spiceLevel: 'Spicy',
            rating: 4.7,
            variants: [
              { id: 'ps-v1', name: 'Regular (8 inch)', price: 299 },
              { id: 'ps-v2', name: 'Medium (10 inch)', price: 449 },
              { id: 'ps-v3', name: 'Large (12 inch)', price: 599 },
            ],
            addons: [
              { id: 'ps-a1', name: 'Extra Cheese Burst', price: 70 },
              { id: 'ps-a2', name: 'Black Olives & Jalapenos', price: 40 },
            ],
          },
          {
            id: 'item-ps-2',
            restaurantId: 'rest-4',
            categoryId: 'cat-ps-1',
            name: 'Farmhouse Garden Fresh Pizza',
            description: 'Fresh bell peppers, sweet corn, mushrooms, black olives, and Italian marinara sauce.',
            price: 249,
            image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&auto=format&fit=crop&q=80',
            isVeg: true,
            isAvailable: true,
            preparationTime: 18,
            spiceLevel: 'Mild',
            rating: 4.6,
          },
        ],
      },
    ],
  },
  {
    id: 'rest-5',
    name: 'Burger Hub',
    slug: 'burger-hub-bhatkal',
    ownerId: 'user-restaurant-1',
    description: 'Smash burgers, crispy fried chicken strips, peri peri crinkle fries, and thick shakes.',
    cuisine: 'Burgers • American • Shakes',
    logo: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200&auto=format&fit=crop&q=80',
    rating: 4.5,
    ratingCount: 520,
    deliveryTimeMin: 15,
    deliveryTimeMax: 25,
    deliveryFee: 20,
    minimumOrder: 120,
    commissionRate: 0.20,
    isOpen: true,
    isVerified: true,
    addressLine: 'College Road, Near Anjuman Campus',
    area: 'Nawayath Colony & Outskirts',
    city: 'Bhatkal',
    latitude: 13.9912,
    longitude: 74.5688,
    menuCategories: [
      {
        id: 'cat-bhb-1',
        restaurantId: 'rest-5',
        name: 'Gourmet Smash Burgers',
        sortOrder: 1,
        items: [
          {
            id: 'item-bhb-1',
            restaurantId: 'rest-5',
            categoryId: 'cat-bhb-1',
            name: 'Crispy Double Cheese Zinger Burger',
            description: 'Juicy double spiced fried chicken fillet topped with cheddar cheese, smoked mayo, and crunchy iceberg lettuce in brioche bun.',
            price: 189,
            image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=80',
            isVeg: false,
            isAvailable: true,
            preparationTime: 15,
            spiceLevel: 'Medium',
            rating: 4.8,
            variants: [
              { id: 'bhb-v1', name: 'Single Fillet', price: 189 },
              { id: 'bhb-v2', name: 'Double Monster Fillet', price: 259 },
            ],
            addons: [
              { id: 'bhb-a1', name: 'Make it a Meal (Fries + Coke)', price: 79 },
              { id: 'bhb-a2', name: 'Extra Cheddar Slice', price: 25 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'rest-6',
    name: 'Cafe Aroma',
    slug: 'cafe-aroma-bhatkal',
    ownerId: 'user-restaurant-1',
    description: 'Artisanal Arabica brews, Belgian waffles, sizzling brownies, and chilled frappes.',
    cuisine: 'Beverages • Desserts • Bakery',
    logo: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200&auto=format&fit=crop&q=80',
    rating: 4.6,
    ratingCount: 430,
    deliveryTimeMin: 15,
    deliveryTimeMax: 25,
    deliveryFee: 20,
    minimumOrder: 100,
    commissionRate: 0.20,
    isOpen: true,
    isVerified: true,
    addressLine: 'Sagar Road Highway Junction',
    area: 'Bhatkal Central',
    city: 'Bhatkal',
    latitude: 13.9833,
    longitude: 74.5645,
    menuCategories: [
      {
        id: 'cat-ca-1',
        restaurantId: 'rest-6',
        name: 'Shakes, Frappes & Desserts',
        sortOrder: 1,
        items: [
          {
            id: 'item-ca-1',
            restaurantId: 'rest-6',
            categoryId: 'cat-ca-1',
            name: 'Belgian Chocolate Overload Shake',
            description: 'Rich Belgian cocoa churned with whole milk and dark chocolate gelato, topped with brownie crumble.',
            price: 160,
            image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&auto=format&fit=crop&q=80',
            isVeg: true,
            isAvailable: true,
            preparationTime: 10,
            rating: 4.8,
          },
          {
            id: 'item-ca-2',
            restaurantId: 'rest-6',
            categoryId: 'cat-ca-1',
            name: 'Warm Choco Lava Cake',
            description: 'Decadent molten chocolate center cake dusted with powdered sugar.',
            price: 110,
            image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80',
            isVeg: true,
            isAvailable: true,
            preparationTime: 10,
            rating: 4.9,
          },
        ],
      },
    ],
  },
];

export const SEED_GROCERY_STORE: GroceryStore = {
  id: 'store-1',
  name: 'Zestora QuickMart — Bhatkal Hub',
  slug: 'zestora-quickmart-bhatkal',
  address: 'Central Distribution Hub, Old Bus Stand Road',
  city: 'Bhatkal',
  rating: 4.9,
  deliveryEta: '10–20 min',
  isOpen: true,
};

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    storeId: 'store-1',
    categoryId: 'gcat-dairy',
    categoryName: 'Dairy & Eggs',
    name: 'Amul Taaza Homogenised Toned Milk',
    brand: 'Amul',
    description: 'Pure, fresh toned milk packed with vital vitamins and calcium.',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&auto=format&fit=crop&q=80',
    mrp: 32,
    price: 30,
    unit: '500 ml',
    stock: 45,
    reserved: 0,
    sku: 'AML-TZ-500',
  },
  {
    id: 'prod-2',
    storeId: 'store-1',
    categoryId: 'gcat-dairy',
    categoryName: 'Dairy & Eggs',
    name: 'Fresh Farm White Eggs (Pack of 6)',
    brand: 'Farm Fresh',
    description: 'Protein-rich clean graded farm white eggs.',
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=400&auto=format&fit=crop&q=80',
    mrp: 55,
    price: 48,
    unit: '6 pcs',
    stock: 60,
    reserved: 0,
    sku: 'EGG-PK-6',
  },
  {
    id: 'prod-3',
    storeId: 'store-1',
    categoryId: 'gcat-bakery',
    categoryName: 'Bakery & Bread',
    name: 'Modern 100% Whole Wheat Brown Bread',
    brand: 'Modern',
    description: 'Freshly baked wholesome brown bread enriched with fiber and grains.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&auto=format&fit=crop&q=80',
    mrp: 50,
    price: 45,
    unit: '400 g',
    stock: 25,
    reserved: 0,
    sku: 'BRD-WHT-400',
  },
  {
    id: 'prod-4',
    storeId: 'store-1',
    categoryId: 'gcat-fruits',
    categoryName: 'Fruits & Vegetables',
    name: 'Farm Fresh Robusta Bananas',
    brand: 'Farm Pick',
    description: 'Naturally ripened, sweet, energy-rich local coastal bananas.',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&auto=format&fit=crop&q=80',
    mrp: 60,
    price: 45,
    unit: '1 kg',
    stock: 35,
    reserved: 0,
    sku: 'FRT-BAN-1KG',
  },
  {
    id: 'prod-5',
    storeId: 'store-1',
    categoryId: 'gcat-fruits',
    categoryName: 'Fruits & Vegetables',
    name: 'Crisp Red Hybrid Tomatoes',
    brand: 'Farm Pick',
    description: 'Hand-picked glossy red firm salad and cooking tomatoes.',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&auto=format&fit=crop&q=80',
    mrp: 40,
    price: 32,
    unit: '1 kg',
    stock: 40,
    reserved: 0,
    sku: 'VEG-TOM-1KG',
  },
  {
    id: 'prod-6',
    storeId: 'store-1',
    categoryId: 'gcat-snacks',
    categoryName: 'Snacks & Munchies',
    name: 'Lay’s India’s Magic Masala Potato Chips',
    brand: 'Lays',
    description: 'Crispy crunchy potato ridges flavored with spicy Indian magic masala.',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&auto=format&fit=crop&q=80',
    mrp: 20,
    price: 20,
    unit: '50 g',
    stock: 80,
    reserved: 0,
    sku: 'SNK-LAYS-MM',
  },
  {
    id: 'prod-7',
    storeId: 'store-1',
    categoryId: 'gcat-beverages',
    categoryName: 'Beverages & Juices',
    name: 'Coca-Cola Zero Sugar Can',
    brand: 'Coca Cola',
    description: 'Crisp sparkling cola taste without sugar and calories.',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&auto=format&fit=crop&q=80',
    mrp: 40,
    price: 38,
    unit: '300 ml',
    stock: 50,
    reserved: 0,
    sku: 'BEV-CCZ-300',
  },
  {
    id: 'prod-8',
    storeId: 'store-1',
    categoryId: 'gcat-staples',
    categoryName: 'Staples & Cooking Oils',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    brand: 'Fortune',
    description: 'Light, healthy cooking oil enriched with Vitamin A & D.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&auto=format&fit=crop&q=80',
    mrp: 145,
    price: 129,
    unit: '1 L Pouch',
    stock: 30,
    reserved: 0,
    sku: 'STP-FTN-1L',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'order-10480',
    orderNumber: 'ZES-20260921-10480',
    customerId: 'user-customer-1',
    customerName: 'Anas Ahmed',
    customerPhone: '+91 98765 43210',
    restaurantId: 'rest-1',
    restaurantName: 'Spice Garden',
    address: {
      id: 'addr-1',
      userId: 'user-customer-1',
      label: 'Home',
      fullName: 'Anas Ahmed',
      phone: '+91 98765 43210',
      addressLine1: 'Flat 302, Green Meadows, Near Shams Mosque',
      area: 'Bhatkal Central',
      city: 'Bhatkal',
      state: 'Karnataka',
      postalCode: '581320',
      latitude: 13.9870,
      longitude: 74.5610,
      isDefault: true,
    },
    items: [
      {
        id: 'oi-1',
        name: 'Special Chicken Biryani (Bhatkali Style)',
        unitPrice: 240,
        quantity: 2,
        totalPrice: 480,
        variantName: 'Regular',
        addons: ['Extra Egg (+₹20)'],
      },
      {
        id: 'oi-2',
        name: 'Crispy Chicken Ghee Roast',
        unitPrice: 260,
        quantity: 1,
        totalPrice: 260,
      },
    ],
    status: 'DELIVERED',
    statusHistory: [
      { status: 'PLACED', note: 'Order placed by customer', timestamp: '2026-09-21T18:10:00Z' },
      { status: 'CONFIRMED', note: 'Payment verified', timestamp: '2026-09-21T18:10:30Z' },
      { status: 'RESTAURANT_ACCEPTED', note: 'Spice Garden kitchen accepted order', timestamp: '2026-09-21T18:12:00Z' },
      { status: 'PREPARING', note: 'Chef started cooking', timestamp: '2026-09-21T18:14:00Z' },
      { status: 'READY_FOR_PICKUP', note: 'Packed and ready on counter', timestamp: '2026-09-21T18:28:00Z' },
      { status: 'PICKED_UP', note: 'Rider Rahul picked up order', timestamp: '2026-09-21T18:32:00Z' },
      { status: 'ON_THE_WAY', note: 'Rider navigating to Shams Mosque', timestamp: '2026-09-21T18:34:00Z' },
      { status: 'DELIVERED', note: 'Delivered securely to customer', timestamp: '2026-09-21T18:45:00Z' },
    ],
    subtotal: 740,
    packagingFee: 20,
    deliveryFee: 30,
    platformFee: 5,
    taxes: 37,
    discount: 50,
    tip: 20,
    totalAmount: 802,
    paymentMethod: 'UPI',
    paymentStatus: 'SUCCESS',
    deliveryType: 'STANDARD',
    deliveryPartnerId: 'user-delivery-1',
    deliveryPartnerName: 'Rahul Naik',
    deliveryPartnerPhone: '+91 94488 55667',
    currentRiderLat: 13.9870,
    currentRiderLng: 74.5610,
    createdAt: '2026-09-21T18:10:00Z',
    updatedAt: '2026-09-21T18:45:00Z',
  },
];
